# Generated by Django 3.1.1 on 2020-10-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20201010_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='User',
            new_name='user',
        ),
    ]
